# Generated by Django 4.2 on 2025-04-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book1',
        ),
    ]
